# Site settings
title: DiversifyImmunology
email: diversifyimmunology@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   The website for DiversifyImmunology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://DiversifyImmunology.github.io" # the base hostname & protocol for your site
twitter_username: DiversifyImmuno
github_username:  diversifyimmunology
array: []

# Build settings
markdown: kramdown

collections:
  instructors:
    output: true
  workshops:
    output: true
  news:
    output: true
